In [1]:
3+2

5

In [2]:
5-3

2

In [3]:
3*2

6

In [4]:
5/2

2.5

In [5]:
5%3

2

In [6]:
5^2

7

In [7]:
5**2

25

In [8]:
clas = 2016

In [9]:
clas

2016

In [10]:
vari = 1

In [12]:
strin = "hello"

In [16]:
flt = 1.5

In [14]:
type(vari)


int

In [17]:
type(flt)

float

In [18]:
type(strin)

str

In [19]:
bol = True

In [20]:
type(bol)

bool

In [24]:
li = [10,20,30,40,50]

In [27]:
li[1:2]

[20]

In [26]:
li[1:2]

[20]

In [28]:
li[1]

20

In [29]:
li[0:3]

[10, 20, 30]

In [31]:
li[0:2]

[10, 20]

In [32]:
li[-2]

40

In [33]:
li[0:-2]

[10, 20, 30]

In [39]:
li[-2:]

[40, 50]

In [40]:
li_2 = [60,70,80]

In [41]:
print(li + li_2)

[10, 20, 30, 40, 50, 60, 70, 80]


In [42]:
lli = li + li_2

In [60]:
for x in lli:
    if x > 15: 
        print(x)
        '/n'
    

20
30
40
50
60
70
80


In [45]:
lli[]>15

SyntaxError: invalid syntax (<ipython-input-45-9a2628c0515f>, line 1)

In [47]:
li


[10, 20, 30, 40, 50]

TypeError: '>' not supported between instances of 'list' and 'int'

In [52]:
lli>15

TypeError: '>' not supported between instances of 'list' and 'int'

In [53]:
print(lli>15)

TypeError: '>' not supported between instances of 'list' and 'int'

In [54]:
35 in lli

False

In [55]:
30 in lli

True

In [56]:
print(30 in lli)

True


In [57]:
li.append(li_2)

In [58]:
li

[10, 20, 30, 40, 50, [60, 70, 80]]

In [64]:
li[5][2]

80

In [65]:
li[5][1]

70

In [66]:
li[5][0]

60

In [67]:
range(1,10,2)

range(1, 10, 2)

In [95]:
print(range(1,10))

range(1, 10)


In [69]:
range(1,3)

range(1, 3)

In [96]:
lli2= list(range(1,11))

In [97]:
lli+lli2

[10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 [1, 2, 3, 4, 5, 6, 'madhu', 8, 9, 10],
 [1, 2, 3, 4, 5, 6, 'madhu', 8, 9, 10],
 [1, 2, 3, 4, 5, 6, 'madhu', 8, 9, 10],
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10]

In [75]:
lii.append(lli2)

NameError: name 'lii' is not defined

In [91]:
lli.append(lli2)

In [78]:
lli

[10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]

In [102]:
print(lli)

[10, 20, 40, 50, 60, 70, 80, [1, 2, 3, 4, 5, 6, 'madhu', 8, 9, 10], [1, 2, 3, 4, 5, 6, 'madhu', 8, 9, 10], [1, 2, 3, 4, 5, 6, 'madhu', 8, 9, 10]]


In [81]:
lli[8][6] = "madhu"

In [92]:
lli[8][6]

'madhu'

In [101]:
del lli[2]

In [100]:
li

[10, 20, 50, [60, 70, 80]]

In [93]:
list(range(0,-1,2))

[]

In [94]:
print(list(range(0,-1,2)))

[]


In [103]:
li[0::2]

[10, 50]

In [104]:
lli[0::2]

[10, 40, 60, 80, [1, 2, 3, 4, 5, 6, 'madhu', 8, 9, 10]]

In [105]:
lli

[10,
 20,
 40,
 50,
 60,
 70,
 80,
 [1, 2, 3, 4, 5, 6, 'madhu', 8, 9, 10],
 [1, 2, 3, 4, 5, 6, 'madhu', 8, 9, 10],
 [1, 2, 3, 4, 5, 6, 'madhu', 8, 9, 10]]

In [106]:
del lli[2]

In [107]:
lli

[10,
 20,
 50,
 60,
 70,
 80,
 [1, 2, 3, 4, 5, 6, 'madhu', 8, 9, 10],
 [1, 2, 3, 4, 5, 6, 'madhu', 8, 9, 10],
 [1, 2, 3, 4, 5, 6, 'madhu', 8, 9, 10]]

In [108]:
lst1 = (1,2,3,4,5,6,7,8,9,10)

In [109]:
lst2 = (1,2,3,4,5,6,7,8,9,10)

In [110]:
lst1[0::2]

(1, 3, 5, 7, 9)

In [111]:
lst[0:1]

NameError: name 'lst' is not defined

In [112]:
lst1(-1::2)

SyntaxError: invalid syntax (<ipython-input-112-4d1846f6ead1>, line 1)

In [113]:
lst1(-1::)

SyntaxError: invalid syntax (<ipython-input-113-e043fae0f476>, line 1)

In [114]:
lst1[-1::2]

(10,)

In [115]:
lst1[-2::-2]

(9, 7, 5, 3, 1)

In [116]:
lst1[-1::-2]

(10, 8, 6, 4, 2)

In [117]:
lst1[-1::]

(10,)

In [119]:
lst100 = list(range(100))

In [120]:
lst100

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [121]:
lst100[-5::-5]

[95, 90, 85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10, 5, 0]

In [123]:
lst100[-4::-6]

[96, 90, 84, 78, 72, 66, 60, 54, 48, 42, 36, 30, 24, 18, 12, 6, 0]

In [124]:
tup = (1,2,3,4)

In [125]:
tup

(1, 2, 3, 4)

In [128]:
tup[0,4]

TypeError: tuple indices must be integers or slices, not tuple

In [131]:
tup[:3]

(1, 2, 3)

In [132]:
tup[:3] = 3

TypeError: 'tuple' object does not support item assignment

In [137]:
fru = {"fruits":["mango","apple","pineapple"],"animals":["lion","tiger","elephant"]}

In [138]:
fru

{'fruits': ['mango', 'apple', 'pineapple'],
 'animals': ['lion', 'tiger', 'elephant']}

In [139]:
fru.values

<function dict.values>

In [140]:
fru.values()

dict_values([['mango', 'apple', 'pineapple'], ['lion', 'tiger', 'elephant']])

In [142]:
fru.keys()

dict_keys(['fruits', 'animals'])

In [143]:
fru.items()

dict_items([('fruits', ['mango', 'apple', 'pineapple']), ('animals', ['lion', 'tiger', 'elephant'])])

In [149]:
fru["fruits"][1] = "no fruit"

In [150]:
fru["fruits"][1]

'no fruit'

In [151]:
fru

{'fruits': ['mango', 'no fruit', 'pineapple'],
 'animals': ['lion', 'tiger', 'elephant']}

In [153]:
lstrep = (1,3,4,2,3,4,5,7,1,2)

In [154]:
lstrep

(1, 3, 4, 2, 3, 4, 5, 7, 1, 2)

In [155]:
lstrep.count

<function tuple.count>

In [156]:
set(lstrep)

{1, 2, 3, 4, 5, 7}

In [171]:
person = 60

In [175]:
if person < 30:
    print("no ticket")
elif person > 30 and person < 50 :
        print("ticket price is 30")
else :
        print("ticket is 50")

ticket price is 30


In [182]:
len(lst100)

100

In [183]:
max(lst100)

99

min(100)

In [184]:
[max(lst100)]

[99]

In [188]:
[max(lstrep)]

[7]

In [1]:
ten = [91:100]

SyntaxError: invalid syntax (<ipython-input-1-c6cd2fd70005>, line 1)

In [2]:
ten = [91::100]

SyntaxError: invalid syntax (<ipython-input-2-19943684f52a>, line 1)

In [3]:
ten = list[range (91:100)]

SyntaxError: invalid syntax (<ipython-input-3-2ab4d5aa01a8>, line 1)

In [4]:
ten = [range(91:100)]

SyntaxError: invalid syntax (<ipython-input-4-0910d88fb5aa>, line 1)

In [5]:
ten = [range(91,100)]

In [6]:
ten


[range(91, 100)]

In [7]:
range(1,100)

range(1, 100)

In [13]:

for x in range(91,101):
    
    
    if x%2 == 0 :
        print(x)
    else :
        print("odd")
        
    

odd
92
odd
94
odd
96
odd
98
odd
100


In [15]:
list(range(91, 101))

[91, 92, 93, 94, 95, 96, 97, 98, 99, 100]

In [16]:
list(range(91,100))

[91, 92, 93, 94, 95, 96, 97, 98, 99]

In [17]:
ten = list(range(91,100))


In [18]:
for x in ten:
    ten[1]

In [19]:
ten[2]

93

In [23]:
for x in len(ten):
    print(ten[x])

TypeError: 'int' object is not iterable

In [24]:
in = [1,2,3]

SyntaxError: invalid syntax (<ipython-input-24-030ff6894658>, line 1)

In [25]:
ind = [1,2,3]

In [26]:
ind2 = [4,5,6]

In [31]:
for i,j in zip(range(0,3),range(1,4)):
    print(i,'+',j,'=',i+j)
    

0 + 1 = 1
1 + 2 = 3
2 + 3 = 5


In [34]:
for i,j in enumerate(range(0,3),range(1,4)):
    print(i,'+',j,'=',i+j)

TypeError: 'range' object cannot be interpreted as an integer

In [37]:
for ind,ind2 in enumerate(range(100,200)):
    print('at',ind,'vale is' ,ind2 )

at 0 vale is 100
at 1 vale is 101
at 2 vale is 102
at 3 vale is 103
at 4 vale is 104
at 5 vale is 105
at 6 vale is 106
at 7 vale is 107
at 8 vale is 108
at 9 vale is 109
at 10 vale is 110
at 11 vale is 111
at 12 vale is 112
at 13 vale is 113
at 14 vale is 114
at 15 vale is 115
at 16 vale is 116
at 17 vale is 117
at 18 vale is 118
at 19 vale is 119
at 20 vale is 120
at 21 vale is 121
at 22 vale is 122
at 23 vale is 123
at 24 vale is 124
at 25 vale is 125
at 26 vale is 126
at 27 vale is 127
at 28 vale is 128
at 29 vale is 129
at 30 vale is 130
at 31 vale is 131
at 32 vale is 132
at 33 vale is 133
at 34 vale is 134
at 35 vale is 135
at 36 vale is 136
at 37 vale is 137
at 38 vale is 138
at 39 vale is 139
at 40 vale is 140
at 41 vale is 141
at 42 vale is 142
at 43 vale is 143
at 44 vale is 144
at 45 vale is 145
at 46 vale is 146
at 47 vale is 147
at 48 vale is 148
at 49 vale is 149
at 50 vale is 150
at 51 vale is 151
at 52 vale is 152
at 53 vale is 153
at 54 vale is 154
at 55 vale is 155
at

name :{'name':'madhureddy','age':22,'DOB',:199}

In [52]:
name = {'A':1,'B': 2, 'C':3}
    

In [39]:
temp = 0
while temp < 10:
    print(temp)
    temp = temp+1

0
1
2
3
4
5
6
7
8
9


In [44]:
name

{'A': 1, 'B': 2, 'C': 3}

In [48]:
name.items()

dict_items([('A', 1), ('B', 2), ('C', 3)])

In [49]:

for i, j in name.items():
    print(i)
    print(j)

A
1
B
2
C
3


In [54]:
6 >= 7 or 7 >= 6

True

In [55]:
10 > 15 and 15 < 10

False

In [56]:
5 != 5 and 6 > 5

False

In [57]:
True != False 

True

In [58]:
True == True and False != True

True

In [59]:
False != False or True != False

True

In [60]:
True = 1 and False = 0

SyntaxError: can't assign to keyword (<ipython-input-60-581b20b97cb1>, line 1)

In [65]:
[i for i in range(11) if i%2 == 0]

[0, 2, 4, 6, 8, 10]

In [66]:
[x for x in lli ]

NameError: name 'lli' is not defined

In [69]:
[i+1 if i%2 == 0 else i-1 for i in range(10)]

[1, 0, 3, 2, 5, 4, 7, 6, 9, 8]

In [88]:




def sumfunction(listin):
    temp = 0
    for x in listin:
        temp = temp+x
    return temp 
    


In [89]:
sumfunction(list(range(0,9)))

36

In [90]:
sumfunction(range(0, 9))

36

In [91]:
sumfunction([1, 2, 3])

6

In [99]:
def my_func(list_arg):
    temp = 0
    [for i in list_arg: temp += 1]
    return var

SyntaxError: invalid syntax (<ipython-input-99-f8b388cf5ef3>, line 3)

In [15]:
def my_max(listinp):
    max = 0
    for x in listinp:
        if x >= max:
            max = x
    return max        

In [16]:
my_max([1,6,20,4])

20

In [13]:
def my_max1(listinp):
    max_ = 0
    return [max_ for x in listinp if x >= max_]

In [11]:
my_max1([1,2,3])

[0, 0, 0]

In [1]:
import numpy as np

In [4]:
        numarry = np.array([1,2,3])

In [5]:
numarry.shape

(3,)

In [6]:
numarry1 = np.array([[1,2,3]])

In [7]:
numarry1.shape

(1, 3)

In [12]:
three = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:

three

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
three.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [15]:
three

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
= three.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [17]:
three.resize((1,9))

In [18]:
three

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [21]:
three[three > 5]

array([6, 7, 8, 9])

In [22]:
three[three % 2 == 0]

array([2, 4, 6, 8])

In [24]:
three[1::2]

array([], shape=(0, 9), dtype=int64)

In [25]:
three

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [31]:
three[1::2]

array([], shape=(0, 9), dtype=int64)

In [32]:
three[1:9]

array([], shape=(0, 9), dtype=int64)

In [37]:
three[9::9]

array([], shape=(0, 9), dtype=int64)

In [43]:
three[0,1::2]

array([2])

In [40]:
three.resize((3,3))

In [41]:
three

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
three[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [52]:
three[-1,]

array([7, 8, 9])

In [54]:
three[2,1] = 999

In [55]:
three[2,1]


999

In [56]:
three

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7, 999,   9]])

In [74]:
cross1 = np.array([ [1,2,3],[4,5,6],[7,8,9]])

In [75]:
cross2 = np.array([ [1,2,3],[4,5,6],[7,8,9]]) 

In [77]:
cross1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
cross2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
np.sum(cross1)

46

In [69]:
cross1.sum()


46

In [71]:
cross1.max()

9

In [76]:
cross1.argmax()

8

In [79]:
cross1.argmin()

0

In [80]:
cross1.std()

2.581988897471611

In [81]:
cross1.mean()

5.0

In [87]:
np.random.randn(3,3) #normal distribution

array([[-1.33741585, -0.79262502, -0.5278093 ],
       [-0.32331545, -1.18797553,  1.06779857],
       [-1.23739279, -0.1898741 , -0.68074643]])

In [88]:
np.random.rand(3,3) #uniform distribution

array([[0.83071061, 0.08555575, 0.62970987],
       [0.92659388, 0.43156699, 0.18432897],
       [0.52474152, 0.60688922, 0.65940733]])

In [93]:
 hun = np.random.randint(0,100,100)

In [94]:
hun.resize(10,10)

In [95]:
hun

array([[ 6,  1, 53, 97, 55, 81, 10, 99, 17, 16],
       [92, 15,  8, 25, 80, 13, 85, 83, 27,  9],
       [76, 95, 65, 11, 86, 21, 76, 14, 11, 92],
       [93, 53, 97, 50, 16, 30, 87, 97, 25, 14],
       [98, 87,  7, 27, 44, 27, 45, 43, 30, 84],
       [71, 63, 35, 14, 11, 88, 39, 60,  6, 23],
       [88, 48,  7, 99, 62, 49, 26, 81, 89, 90],
       [86, 20, 64, 10, 44, 80, 89, 35, 70,  2],
       [42, 92, 76, 79, 81,  2, 31, 83, 98, 15],
       [81, 25, 60, 87, 37, 95,  3, 86, 66, 85]])

In [100]:
rando = np.random.randint(90,100,10)

In [97]:
rando

[array([98, 99, 90, 90, 93, 95, 92, 91, 90, 94])]

In [98]:
rando * hun

array([[ 588,   99, 4770, 8730, 5115, 7695,  920, 9009, 1530, 1504],
       [9016, 1485,  720, 2250, 7440, 1235, 7820, 7553, 2430,  846],
       [7448, 9405, 5850,  990, 7998, 1995, 6992, 1274,  990, 8648],
       [9114, 5247, 8730, 4500, 1488, 2850, 8004, 8827, 2250, 1316],
       [9604, 8613,  630, 2430, 4092, 2565, 4140, 3913, 2700, 7896],
       [6958, 6237, 3150, 1260, 1023, 8360, 3588, 5460,  540, 2162],
       [8624, 4752,  630, 8910, 5766, 4655, 2392, 7371, 8010, 8460],
       [8428, 1980, 5760,  900, 4092, 7600, 8188, 3185, 6300,  188],
       [4116, 9108, 6840, 7110, 7533,  190, 2852, 7553, 8820, 1410],
       [7938, 2475, 5400, 7830, 3441, 9025,  276, 7826, 5940, 7990]])

In [103]:
rando = rando.T

In [104]:
np.dot(hun,rando)

array([40648, 41065, 51684, 53074, 46716, 38730, 60315, 46828, 56120,
       59112])

In [106]:
rando_copy = rando.copy

In [107]:
rando

array([99, 94, 95, 93, 91, 92, 91, 95, 92, 98])

In [117]:
rando_copy = rando.copy

In [118]:
rando_copy[0] = 111

TypeError: 'builtin_function_or_method' object does not support item assignment

In [119]:
rando_copy

<function ndarray.copy>

In [120]:
import pandas as pd

In [132]:
pd.Series(['ABC','DEF','GHI'])

0    ABC
1    DEF
2    GHI
dtype: object

In [139]:
panddict = {'dic1':['ABC'],'dic2':['DEF'],'dic3':['GHI']}

In [140]:
pd.Series(panddict)

dic1    [ABC]
dic2    [DEF]
dic3    [GHI]
dtype: object

In [135]:
import pandas as pd

In [136]:
pd.Series(np.array(['ABC','DEF','GHI']))

0    ABC
1    DEF
2    GHI
dtype: object

In [137]:
mydir = {'myname':['Madhu','23','1995'],'myfriend':['vishnu','23','1994']}

In [138]:
pd.Series(mydir)

myname       [Madhu, 23, 1995]
myfriend    [vishnu, 23, 1994]
dtype: object

In [143]:
mydir1 = {'name':['madhu','vishnu'],'Age':[22,23],'DOB':[1994,1993]}

In [144]:
pd.Series(mydir1)

name    [madhu, vishnu]
Age            [22, 23]
DOB        [1994, 1993]
dtype: object

In [149]:
listdir = ('name'('madhu','manu'))

TypeError: 'str' object is not callable

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame(data  = pos,index_name , columns= 1)

SyntaxError: positional argument follows keyword argument (<ipython-input-2-4731f254c493>, line 1)

In [3]:
name = ["apple","Amazon","google"]

In [4]:
position = [1,2,3]

In [5]:
price = ["$1000","$800","$600"]

In [29]:
df = pd.DataFrame(position,name,columns=['position'])

In [30]:
df

position
apple          1
Amazon         2
google         3

In [31]:
df['price'] = price

In [32]:
df

position  price
apple          1  $1000
Amazon         2   $800
google         3   $600

In [40]:
df.reset_index(inplace= True)

In [41]:
df

index  level   names  position  price
0      0      0   apple         1  $1000
1      1      1  Amazon         2   $800
2      2      2  google         3   $600

In [46]:
df.columns = ["level1","level2","names","price","position"]

In [47]:
df

level1  level2   names  price position
0       0       0   apple      1    $1000
1       1       1  Amazon      2     $800
2       2       2  google      3     $600

In [53]:
del df["level1"]

In [54]:
df

level2   names  price position
0       0   apple      1    $1000
1       1  Amazon      2     $800
2       2  google      3     $600

In [55]:
del df["level2"]

In [58]:
df.drop("price",inplace= True,axis=1)

In [59]:
df

names position
0   apple    $1000
1  Amazon     $800
2  google     $600

In [60]:
df.set_index("names",inplace=True)

In [61]:
df

position
names          
apple     $1000
Amazon     $800
google     $600

In [62]:
df.head

<bound method NDFrame.head of        position
names          
apple     $1000
Amazon     $800
google     $600>

In [63]:
df.head()

position
names          
apple     $1000
Amazon     $800
google     $600

In [4]:
from sklearn import datasets

In [5]:
irish = datasets.load_iris

In [12]:
irish()

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  